on: workflow_dispatch

jobs:
  fuzz_sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 12
          platform: x64
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'
      - name: Make fuzzer script executable
        run: chmod +x ./fuzzing/fuzzer.sh
      - name: Run fuzzer
        run: ./fuzzing/fuzzer.sh
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fuzz_sample_artifact
          path: fuzzing/artifacts
